facebook:
  label: Facebook
  permalink: /facebook
  description: Facebook tag description

hello:
  label: Hello
  permalink: /hello
  description: Hello tag description

docusaurus:
  label: Docusaurus
  permalink: /docusaurus
  description: Docusaurus tag description

hola:
  label: Hola
  permalink: /hola
  description: Hola tag description

release:
  label: Release
  permalink: /release
  description: Release announcements

chromium:
  label: Chromium
  permalink: /chromium
  description: Chromium-specific runtime updates

nodejs:
  label: Node.js
  permalink: /nodejs
  description: Node.js automation and server-side development

dxf:
  label: DXF
  permalink: /dxf
  description: DXF file format and generation

automation:
  label: Automation
  permalink: /automation
  description: CAD and workflow automation

cad:
  label: CAD
  permalink: /cad
  description: Computer-Aided Design tools and techniques

ai:
  label: AI
  permalink: /ai
  description: Applied AI for CAD and manufacturing workflows

llm:
  label: LLM
  permalink: /llm
  description: Large Language Model automation patterns

python:
  label: Python
  permalink: /python
  description: Python scripting for CAD and data automation

solidworks:
  label: SolidWorks
  permalink: /solidworks
  description: SolidWorks macros, API usage, and automation
